# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish Map Data

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
      
      - name: Build publish data
        run: npm run build --if-present

      - name: Commit changed to publish branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Deploy to publish
          branch: publish-test
          # repository: ./dist
          skip_dirty_check: true 
          commit_user_name: ocp-bot
          commit_user_email: ocp-bot@open-contracting.org
          push_options: '--force'
